[package]
name = "smpl_script"
version = "0.0.1"
authors = ["Galileo Cappella"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
